config/routes.rb
Gratitude::Application.routes.draw do
  resources :graces

  resources :days do
    resources :graces
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root :to => "days#index"

  

end

app/models/day.rb
class Day
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :graces

  field :favorite, type: Mongoid::Boolean

  index({ favorite: 1 })
end

app/models/grace.rb
class Grace
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :day

  field :description, type: String
end

app/models/user.rb
class User
  include Mongoid::Document

  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :oauth_token, type: String
  field :oauth_expires_at, type: Time

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:favorite)
    end
end

app/controllers/graces_controller.rb
class GracesController < ApplicationController
  before_action :load_day
  before_action :set_grace, only: [:show, :edit, :update, :destroy]

  # GET /graces
  # GET /graces.json
  def index
    @graces = @day.graces
  end

  # GET /graces/1
  # GET /graces/1.json
  def show
  end

  # GET /graces/new
  def new
    @grace = @day.graces.build
  end

  # GET /graces/1/edit
  def edit
  end

  # POST /graces
  # POST /graces.json
  def create
    @grace = @day.graces.build(grace_params)

    respond_to do |format|
      if @grace.save
        format.html { redirect_to [@day, @grace], notice: 'Grace was successfully created.' }
        format.json { render action: 'show', status: :created, location: @grace }
      else
        format.html { render action: 'new' }
        format.json { render json: @grace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graces/1
  # PATCH/PUT /graces/1.json
  def update
    respond_to do |format|
      if @grace.update(grace_params)
        format.html { redirect_to [@day, @grace], notice: 'Grace was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @grace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graces/1
  # DELETE /graces/1.json
  def destroy
    @grace.destroy
    respond_to do |format|
      format.html { redirect_to day_graces_url(@day) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grace
      @grace = @day.graces.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grace_params
      params.require(:grace).permit(:description)
    end

    def load_day
      @day = Day.find(params[:day_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/graces_helper.rb
module GracesHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :favorite %><br>
    <%= f.check_box :favorite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<% @days.each do |day| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= day.id %>
    </div>
      <ul class="list-group">
      <% day.graces.each do |grace| %>
        <li class="list-group-item"><%= grace.description %></li>
      <% end %>
      <li class="list-group-item">
        <%= link_to 'New Grace', new_day_grace_path(day), :class => "btn btn-default" %>
      </li>
      </ul>
      <div class="panel-body">
      <%= link_to 'Delete this day', day, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
  </div>
<% end %>

<br>
<%= link_to 'New Day', new_day_path, :class => "btn btn-default" %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Favorite:</strong>
  <%= @day.favorite %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/graces/_form.html.erb
<%= form_for([@day, @grace]) do |f| %>
  <% if @grace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grace.errors.count, "error") %> prohibited this grace from being saved:</h2>

      <ul>
      <% @grace.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graces/edit.html.erb
<h1>Editing grace</h1>

<%= render 'form' %>

<%= link_to 'Show', day_grace_path(@day, @grace) %> |
<%= link_to 'Back', day_graces_path(@day) %>

app/views/graces/index.html.erb
<h1>Listing graces</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @graces.each do |grace| %>
      <tr>
        <td><%= grace.description %></td>
        <td><%= link_to 'Show', day_grace_path(@day, grace) %></td>
        <td><%= link_to 'Edit', edit_day_grace_path(@day, grace) %></td>
        <td><%= link_to 'Destroy', [@day, grace], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grace', new_day_grace_path(@day) %>

app/views/graces/new.html.erb
<h1>New grace</h1>

<%= render 'form' %>

<%= link_to 'Back', day_graces_path(@day) %>

app/views/graces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @grace.description %>
</p>

<%= link_to 'Edit', edit_day_grace_path(@day, @grace) %> |
<%= link_to 'Back', day_graces_path(@day) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Gratitude</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div id="user-widget" class="page-header">
	  <% if current_user %>
	    Welcome <strong><%= current_user.name %></strong>!
	    <%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>

  <h1>Gratitude</h1>
  <%= yield %>
</div>
</body>
</html>